name: Snake Game

on:
  schedule:
    - cron: '0 */5 * * *'   # a cada 5 horas
  workflow_dispatch:        # permite disparar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Puxa o repositório completo (incluindo history)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Prepara a pasta de saída antes de gerar o SVG
      - name: Prepare output folder
        run: mkdir -p dist

      # 3) Gera o snake baseado nos teus commits
      - name: Generate snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Arturito2005
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 4) Comita automaticamente o SVG gerado
      - name: Commit updated SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}      # <— obrigatório!
          commit_message: 'chore: update snake animation'
          file_pattern: 'dist/github-contribution-grid-snake.svg'
